### ISSUE TITLE
想请问一下怎么进行ssh远程访问

### ISSUE THREAD

**Issue by shanette1** [Pluto-Whong/natcross2#2]
直接ssh -pListenPort user@ServiceIp 吗

**Comment by Pluto-Whong** [comment]
是这样的。

需要相应的客户端线程目标destIp:destPort映射到内网ssh的IP:端口。

**Comment by shanette1** [comment]
![图片](https://user-images.githubusercontent.com/38215052/80079881-6d594b80-8583-11ea-83af-3e0672a29104.png)

这边我做了映射，然后用上面那个命令好像不行

**Comment by Pluto-Whong** [comment]
服务端部署的情况呢？

然后看你的截图好像是windows的idea，你确定127.0.0.1有ssh端口？

**Comment by shanette1** [comment]
服务端是一样的，　我这个是ubuntu的IDEA,　服务器是阿里云，listenPort是8081，servicePort是10010,服务器入口端也开放了，ssh端口默认不是22端口吗？所以我这个就设置的22端口，127.0.0.1就是我想内网穿透的电脑，然后我用命令ssh -p8081 user@aliyun想试一下能不能做穿透，ssh我还需要修改系统配置文件吗？

**Comment by Pluto-Whong** [comment]
你的配置看起来也是正确的，应该是其他问题造成的，先确认下客户端是否可以和服务端互通吧，首先问一下，你测试过像tomcat这样的隧道没？如果能通的话我们再考虑下ssh的问题。

**Comment by shanette1** [comment]
因为我看了一下源码，tomcat这种我觉得应该是ok的，因为拿到socket进行转发就行，但是我看了源码部分好像没有处理ssh交互这块，所以就比较疑惑，因为我也看了lanproxy，网上基本上都是访问内网网站。

**Comment by Pluto-Whong** [comment]
你还是先尝试打通tomcat吧，不管是ssh还是其他的也好，凡是没有 协议中IP描述 需要和 物理连接IP 相同的都是可以直接通过该APP进行的（FTP这种动态端口也除外）。

你在这个应用上的配置是没有问题的，应该是其他问题，建议使用TOMCAT这种简单的应用先打通验证下比较好。

想起一点，你的serviceIp改成你的aliyunIP了没？

**Comment by shanette1** [comment]
好　我试一下，serviceIp也改了
