### ISSUE TITLE
请问下这个可以穿透远程桌面嘛

### ISSUE THREAD

**Issue by dzjfromChina** [Pluto-Whong/natcross2#3]
请问下这个可以穿透远程桌面嘛

**Comment by Pluto-Whong** [comment]
可以的，所有单端口TCP模式的都可以用这各做穿透使用。

**Comment by dzjfromChina** [comment]
只要改成destIp= 3389 即可还是需要修改部分代码?

**Comment by Pluto-Whong** [comment]
destPort改成3389，如果你的客户端部署到了本机，destIp用127.0.0.1就好了
