### ISSUE TITLE
Server运行时 LengthChannel的read方法中读出的长度很大

### ISSUE THREAD

**Issue by w9029** [Pluto-Whong/natcross2#5]
server端运行时，穿透功能正常，但是打开10010端口的网页会触发一个问题，就是在LengthChannel类中读出的length非常的大，后续的json解析也无法进行，并且这个length似乎是一个固定值，1195725856
请问你遇到过这个问题嘛？或者你有什么头绪嘛？

**Comment by Pluto-Whong** [comment]
讲道理，10010是控制端口，是提供给客户端交互使用的，不应该出现打开网页的情况（换句话说就是，10010不得作为暴露端口使用）。
你的情况应该是将10010作为暴露端口进行访问了，这个固定值是HTTP协议最前面4个字节基本是固定的原因（其实这也是废话，10010就不应当作为HTTP端口进行访问）

**Comment by w9029** [comment]
谢谢解答。。那应该就是我理解错了，我以为你在10010挂了http页面。
另外我想问下，如果要开起http页面管理，是需要把你的另一个项目natcross-boot加进来嘛？
我看到里面引用了natcross2中的类，是需要把两个项目放到一个目录里？
还有。。natcross-boot中好像用sqlite存储了用户信息，关数据库结构有相关的文档参考吗

不好意思一下问了这么多。。。

**Comment by w9029** [comment]
大师我悟了。。刚刚那些问题我都懂了
