### ISSUE TITLE
这个怎么设定那些参数，ip地址，端口号？ 哪个配置文件还是命令行参数传入，我搜的时候没找到？

### ISSUE THREAD

**Issue by kaiduohong** [Pluto-Whong/natcross2#6]
就是依赖它的natcross-boot和natcross-boot-client。这两个不是需要端口号什么的一些配置吗？怎么弄呢？

**Comment by Pluto-Whong** [comment]
如果你是用natcross-boot的话，部署好，从web进行管理就好了

**Comment by kaiduohong** [comment]
> 如果你是用natcross-boot的话，部署好，从web进行管理就好了

client里面的配置文件NATCROSS_HTTP_SERVER和NATCROSS_CLIENT_SERVER_IP有什么区别。不应该都改成公网机器的ip吗？ 为什么会向服务器获取监听状态异常

**Comment by Pluto-Whong** [comment]
没什么区别的，只不过当时写的时候，为了区分http协议的URL前缀和IP，这里写了两个纯粹是惯性思维（另一个原因是，HTTP交互可以作为控制端口，ip是最终服务的机器地址，所以如果做的更多了，是可以将最终服务的机器进行多示例部署的）
