### ISSUE TITLE
建立控制通道失败

### ISSUE THREAD

**Issue by 516140852** [Pluto-Whong/natcross2#8]
09:53:34,999 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:53:35,000 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6956de9 - Registering current configuration as safe fallback point

09:53:56.012 [main      ] [p.p.n.c.a.InteractiveSimpleClientAdapter     ] [ERROR] [99  ] - 向服务端[47.112.155.11:8828]建立控制通道失败

**Comment by Pluto-Whong** [comment]
确认下通道端口是否正确，然后防火墙是否正确放通

**Comment by 516140852** [comment]
防火墙都是关闭的，端口都是开放的

**Comment by Pluto-Whong** [comment]
加群交流吧，q群：438793541，你应该是第一个😂

**Comment by Pluto-Whong** [comment]
最终问题结论：云服务器防火墙没有放通
